### ISSUE TITLE
Traceback (most recent call last):   File "fansly_downloader.py", line 1006, in hash_img PermissionError: [WinError 32] The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by ForcedToRock** [Avnsx/fansly-downloader#106]
I just updated to version 0.4 and got that message when running the downloader. I was trying to update a previously scraped model profile.

**Comment by Avnsx** [comment]
Reboot pc, whitelist Fansly Downloader with your anti virus program and try again

**Comment by ForcedToRock** [comment]
Still have the issue.

**Comment by Avnsx** [comment]
Something is using the images it's trying to hash already. Are you trying to maybe run multiple versions of fansly downloader at once or something? Or maybe you're viewing some images, with another program while you're trying to run the downloader?

**Comment by ForcedToRock** [comment]
The issue persisted, I couldn't remove the read-only option. I'd keep trying but it would revert to read-only. Weirdly, after starting again, it still showed that error message 3 times for GIF files located in the Messages>Videos directory, then the program ran just fine. Downloading stuff and whatnot.

**Comment by Avnsx** [comment]
I think I know why this happend, in line:
https://github.com/Avnsx/fansly-downloader/blob/115d549204268db8a5bf6d7bd5b425c8add1d71c/fansly_downloader.py#L1003
I open the image with the python PIL module, but I forgot to close it. So the resource is not instantly released again, which might've caused this error.
