### ISSUE TITLE
Can't download content from a creator whose username is longer than 20 characters.

### ISSUE THREAD

**Issue by ArcaTwin** [Avnsx/fansly-downloader#107]
Could you expand the requirement? It's the only error I'm getting.

**Comment by Avnsx** [comment]
Well how many characters is it?

Go here and copy paste the username https://wordcounter.net/character-count

Also it shouldn't be possible for it to be above 20 characters, I came up with that 4 to 20 bdcause that's the fansly username requirments

**Comment by Avnsx** [comment]
@ArcaTwin what creator name even is it, so I can verify that there's actually a creator whose name is above 20 characters.

**Comment by ArcaTwin** [comment]
@Christian_AlexanderXXX

Well, I'm not sure what could be wrong, but I just can't get it to work. Also, the script automatically deletes the "@" from the username when I run it.

**Comment by Avnsx** [comment]
Yeah removing the @ is normal, intended behaviour.

I really wonder how that guy got that name, when the maximum character count you can sing up with is 20 characters...

Anyways I will fix that in version 0.4.1

Thanks for letting me know!

**Comment by ArcaTwin** [comment]
Thank you! So should I update the file? I'm using the windows version.

**Comment by Avnsx** [comment]
No it's going to take a while until I release that 0.4.1 version as executable, but I can release a commit to the python version which would fix this issue.

**Comment by Avnsx** [comment]
I have made several commits that address this issue. Please download the [latest python version](https://github.com/Avnsx/fansly-downloader#python-version-requirements) of the repository and let me know if those changes, solve your issue.

**Comment by Avnsx** [comment]
The Executable file that finally fixes this bug, is now also officially released, if you're on the previous 0.4 executable version, start it and it'll automatically update itself.

Else you can download it from [releases](https://github.com/Avnsx/fansly-downloader/releases/latest).
