### ISSUE TITLE
Doesn't download message content anymore

### ISSUE THREAD

**Issue by Rocket3192** [Avnsx/fansly-downloader#111]
Hello, I used this software since multiple months now and it always worked great, but since the last update (I believe) it doesn't download message content anymore it says :
 Info | 17:05 || Initiating Messages procedure. Standby for results.
 Info | 17:05 || Amount of Media in Messages with [creator name censored]: 0 (scrapable: 0)
 
 Even tho i have messages from this creator and I can download those pictures with a chrome extension 
 
 Thanks

PS : I used the last version available

**Comment by Avnsx** [comment]
Already know about this issue and it's already solved, the fix will be live in version 0.4.1.

Which might release in a week, or two.

**Comment by Avnsx** [comment]
I have made several commits that address this issue. Please download the [latest python version](https://github.com/Avnsx/fansly-downloader#python-version-requirements) of the repository and let me know if those changes, solve your issue.

**Comment by Rocket3192** [comment]
> I have made several commits that address this issue. Please download the [latest python version](https://github.com/Avnsx/fansly-downloader#python-version-requirements) of the repository and let me know if those changes, solve your issue.

Windows Defender detects the repository zip as a Trojan

**Comment by Rocket3192** [comment]
It doesn't detect anymore but it did 
![image](https://github.com/Avnsx/fansly-downloader/assets/123319690/c8a0952a-a993-4130-8b4e-7b24dc3e6d40)

**Comment by Rocket3192** [comment]
Okay so i installed everything and it seems like it's working fine now :)
