### ISSUE TITLE
[Replace with descriptive keypoint title]

### ISSUE THREAD

**Issue by mcrownover** [Avnsx/fansly-downloader#114]
**IMPORTANT:** Be sure to replace all ``{{`` template sections ``⚠️}}`` or your issue may be discarded.

## Bug Description
Not downloading Subscribed content, and only 1 of the accounts I follow

## Expected behavior
To download all media from the subscribed model accounts

## Actual behavior
It downloaded the "free" preview files from 1 of the 6 accounts I follow
I am only subscribed to 1 model and did not get anything from that one.

*( If applicable, [add screenshots](https://stackoverflow.com/a/14494775/15163882) to help explain your problem. )*
https://ibb.co/f04yGzM
https://ibb.co/sRQHPR2

## Environment Information
 - Operating System: Windows 11
 - Fansly Downloader Version: v0.4
 - Fansly Downloader Type: Executable
 - Specific creators name: @sublinella

## User Research
*( fill ``[ ]`` with ``x``, if you've already done said task )*

I have done the following:
- [x] Looked through [old GitHub issues](https://github.com/Avnsx/fansly-downloader/issues?&q=is%3Aissue)
- [x] Read the [config.ini options](https://github.com/Avnsx/fansly-downloader/wiki/Explanation-of-provided-programs-&-their-functionality#explanation-of-configini)
- [x] Searched on [Google](https://www.google.com/search?q=how+do+I+foo)

## Additional context
I am happy to share my user/pass with you if needed.

**Comment by Avnsx** [comment]
Only one username at a time for ``config.ini`` > ``TargetedCreator`` > ``username``

**Comment by mcrownover** [comment]
My bad.  I misread the info for the config.ini   Thanks :)
