### ISSUE TITLE
.exe file compromised?

### ISSUE THREAD

**Issue by NoisyNinja343** [Avnsx/fansly-downloader#118]
## Bug Description
AVG Win64:Trojan-gen

## Expected behavior
.exe file to exist within folder

## Actual behavior
AVG is quarantining the .exe file stating it is infected with malware (Win64:Trojan-gen). Appears the .exe is trying to update, and after restoring (not making an exception) it happens again

## Environment Information
 - Operating System: Windows 11
 - Fansly Downloader Version: Unknown - can't open .exe
 - Fansly Downloader Type: .exe
 - Specific creators name: n/a

## User Research

I have done the following:
- [X] Looked through [old GitHub issues](https://github.com/Avnsx/fansly-downloader/issues?&q=is%3Aissue)
- [X] Read the [config.ini options](https://github.com/Avnsx/fansly-downloader/wiki/Explanation-of-provided-programs-&-their-functionality#explanation-of-configini)
- [X] Searched on [Google](https://www.google.com/search?q=how+do+I+foo)

## Additional context
Anyone else having this issue (as of 28062023 @ 1250 EST?)
Love the program, but not willing to trash my PC if the files have been compromised.

**Comment by Avnsx** [comment]
Congratulations, you won the lottery and are successfully banned from interacting with the repository.

It was to hard to read the FAQ real quick, wasn't it. Neither is this a Bug but should've been a discussion if anything.

Q: "Why do some executables show detections on them in VirusTotal?"
A: The Fansly Downloader executables are not [digitally signature signed](https://www.digicert.com/signing/code-signing-certificates), as it comes with continous prohibitively expensive costs. So the executables tend to produce alot of false positives (invalid detections). Instead each release of the scraper is e-mailed to antivirus providers for manual analysis, and the not 💩 providers actually analyse and unflag them, while others don't even bother reading their e-mails, but for some reason managed to get on VirusTotals file scanning system. If you're knowledgeable with the python programming language; any [pyinstaller](https://github.com/pyinstaller/pyinstaller) compiled python executable, such as Fansly Downloader, is de-compileable with e.g. [uncompyle6](https://github.com/rocky/python-uncompyle6/), so you could additionally assure yourself that no harmful code is being distributed to your local machine.
