### ISSUE TITLE
Error while displaying the rich progress bar in version 0.4.1

### ISSUE THREAD

**Issue by Avnsx** [Avnsx/fansly-downloader#119]
_Originally posted by @IssusZak in https://github.com/Avnsx/fansly-downloader/discussions/117#discussioncomment-6306997_

![gjvjhv](https://github.com/Avnsx/fansly-downloader/assets/136801174/b52acd5b-2bbe-46ab-911d-c035de7cbe11)

Hello, thanks for the 0.4.1 I can ddl the dm again

I left the program running to simply see if there were any errors and return if error or no error,  and I got this message. (I just have to click on Enter for it to continue).

otherwise there's no problem

edit :  I may have found the error, the creator uploaded a set at the same time, the message may have come from there (the time corresponds).

**Comment by IssusZak** [comment]
I downloaded the scalper again and got this message near the end.

I translate the message into French: 
an established connection has been interrupted by software on your host computer
![Capture d’écran 2023-06-29 175421](https://github.com/Avnsx/fansly-downloader/assets/136801174/996ba227-2298-4f59-85be-342f862524d9)

the config file is the same as before

**Comment by Avnsx** [comment]
Try connecting through a VPN and then downloading.

Also try excluding the download folder or the file from your anti virus program.

**Comment by IssusZak** [comment]
I don't have the problem with others and I wanted to re ddl with the creator and I didn't get any more error messages (I was able to ddl all the test content (6k images) without any problem)

but I think you're right I'm also leaning towards the internet connection (I'd avoid having twitch + social network open during ddl)

sorry for this inconvenience
