### ISSUE TITLE
'Connection aborted' while downloading m3u8 file

### ISSUE THREAD

**Issue by xyzbnc** [Avnsx/fansly-downloader#133]
## Bug Description
m3u8 file appears to download well initially, but as the download continues it stalls, and finally gives the error ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

## Environment Information
 - Operating System: Windows
 - Fansly Downloader Version: v0.4.1
 - Fansly Downloader Type: Executable
 - Specific creators name: LilyMaeExhib

I have done the following:
- [x] Looked through [old GitHub issues](https://github.com/Avnsx/fansly-downloader/issues?&q=is%3Aissue)
- [x] Read the [config.ini options](https://github.com/Avnsx/fansly-downloader/wiki/Explanation-of-provided-programs-&-their-functionality#explanation-of-configini)
- [x] Searched on [Google](https://www.google.com/search?q=how+do+I+foo)

**Comment by Avnsx** [comment]
Did this happen once or does his repeadetly happen with the same specific m3u8 video? If yes; how long is the video?

Also did you try connecting to a VPN before starting the download?

**Comment by xyzbnc** [comment]
Thanks Mika. It happens on every different m3u8. The videos appear to be 20min+ usually.

I'll try my VPN & WARP as well - thank you. Will update shortly.

**Comment by xyzbnc** [comment]
Update: my VPN seemed, if anything, to force the process to fail sooner. WARP, however, is working great. Thanks!
