### ISSUE TITLE
Doesn't seem to work anymore 8/15/23

### ISSUE THREAD

**Issue by br00tal** [Avnsx/fansly-downloader#139]
When running the executable or manually pasting into the developer console, this error is now presented - net::ERR_BLOCKED_BY_CLIENT

**Comment by Avnsx** [comment]
This is completly wrong information and that error you posted is from chrome's devtools and is completly unreleated to fansly-downloader.

Fansly-Downloader works completly fine and the problem is on your side.

Finally this is not a topic for the issues section of this github project.
