### ISSUE TITLE
MAC Os issue

### ISSUE THREAD

**Issue by jinxthejiv27** [Avnsx/fansly-downloader#144]
I've been trying this out for a minute but i cant seem to get it to work. When i try to open the downloader i get this error:
jalenvenable@Jalens-Mac-mini fansly-downloader-0.3.5 % /Users/jalenvenable/Downloads/fansly-downloader-0.3.5/fansly_scraper.py
/Users/jalenvenable/Downloads/fansly-downloader-0.3.5/fansly_scraper.py: line 1: import: command not found
/Users/jalenvenable/Downloads/fansly-downloader-0.3.5/fansly_scraper.py: line 2: from: command not found
/Users/jalenvenable/Downloads/fansly-downloader-0.3.5/fansly_scraper.py: line 3: from: command not found
/Users/jalenvenable/Downloads/fansly-downloader-0.3.5/fansly_scraper.py: line 4: from: command not found
/Users/jalenvenable/Downloads/fansly-downloader-0.3.5/fansly_scraper.py: line 5: from: command not found
/Users/jalenvenable/Downloads/fansly-downloader-0.3.5/fansly_scraper.py: line 6: from: command not found
/Users/jalenvenable/Downloads/fansly-downloader-0.3.5/fansly_scraper.py: line 7: from: command not found
/Users/jalenvenable/Downloads/fansly-downloader-0.3.5/fansly_scraper.py: line 8: from: command not found
/Users/jalenvenable/Downloads/fansly-downloader-0.3.5/fansly_scraper.py: line 9: from: command not found
/Users/jalenvenable/Downloads/fansly-downloader-0.3.5/fansly_scraper.py: line 10: from: command not found
/Users/jalenvenable/Downloads/fansly-downloader-0.3.5/fansly_scraper.py: line 11: syntax error near unexpected token `'title Fansly Scraper''
/Users/jalenvenable/Downloads/fansly-downloader-0.3.5/fansly_scraper.py: line 11' `os.system('title Fansly Scraper')

I even get the same message on the latest version. any idea why?

**Comment by Avnsx** [comment]
Re-open a issue ticket, properly filling it out with information regarding the issue with the current latest version of fansly-downloader 0.4.1
