### ISSUE TITLE
Paid content - download mode

### ISSUE THREAD

**Issue by god43** [Avnsx/fansly-downloader#154]
what does this collection mode mean exactly? like if i leave my settigns to normal will I not download paid content?

download_mode: Determines what parts of a fansly creator's content should be scraped. You can choose from the following values:

    Normal: Downloads Timeline + Messages one after another.
    Timeline: Scrapes only the creator's timeline content.
    Messages: Scrapes only the creator's messages content.
    Single: Fetch a single post by the post's ID. Click on a post to see its ID in the url bar e.g. ../post/1283493240234
    Collection: Download all content listed within the ["Purchased Media Collection"](https://fansly.com/collection)

**Comment by Avnsx** [comment]
https://github.com/Avnsx/fansly-downloader/issues/148
