### ISSUE TITLE
Downloaded video has a 2-seconds of empty space before the start of the video.

### ISSUE THREAD

**Issue by RalkeyOfficial** [Avnsx/fansly-downloader#89]
This problem is kinda difficult to explain and very random, but I will do my best.

I just ran the download and most of the videos have this time before the start of the video where nothing happens.

Sometimes the video starts instant, and sometimes the video has 2 seconds of nothing at the start.
The audio will also start playing in these 2 seconds of emptiness.

It's not necessarily a massive issue as the video does play after those 2 seconds, but it's definitely not intended.

**Comment by Avnsx** [comment]
I had someone test that [m3u8 function](https://github.com/Avnsx/Fansly-Downloader-App/blob/3f502613c1e5f673c3e45ab120039c047ecf3a22/Fansly_Downloader.py#L394) I wrote before and they also have that same issue.

Unfortunately for me it never happens though, so I'm not sure how I can fix a bug that won't replicate on my local system and currently also have no clue why that happens

**Comment by Avnsx** [comment]
Does this maybe happen for you @UpAndDown666 and could you please help me fix this?

**Comment by Avnsx** [comment]
Should be fixed with commit https://github.com/Avnsx/Fansly-Downloader-App/commit/2736a5417d0a6db75f56064371b305fdaafcd52b

**Comment by Avnsx** [comment]
Closing, as the [0.4 version is finally released](https://github.com/Avnsx/fansly-downloader/releases/tag/v0.4) and does target & solve the topics mentioned within this issue.

If you're on the previous 0.3.5 version you can comfortably update using the ``updater.exe`` supplied in the version, or just manually download the 0.4 version from the [repositories Releases](https://github.com/Avnsx/fansly-downloader/releases/tag/v0.4).
