### ISSUE TITLE
"No scrapeable media found in mesages"

### ISSUE THREAD

**Issue by 3my** [Avnsx/fansly-downloader#96]
I get "No scrapeable media found in mesages" even when there are 3 pictures available.
Using Chrome and the latest version of the downloader, also tried with Firefox but I got the same error.

**Comment by Avnsx** [comment]
Are you using version 0.4 through python? what creator is this happening with

**Comment by 3my** [comment]
Oh no I'm using 0.3.5 through the .exe, happening with user "iamyourkittygirl"

**Comment by Avnsx** [comment]
Use 0.4 through python instead or wait a week or something until I compile it as executable

https://github.com/Avnsx/fansly-downloader#%EF%B8%8F-set-up
